In [ ]:
from xverse.transformer import WOE
import pandas as pd

import os
os.getcwd()
import sys
sys.path.append("c:/credit-risk-model")

df = pd.read_csv("../data/raw/data.csv")

In [15]:
from src.default_estimator import create_proxy_target

rfm = create_proxy_target(df)

rfm.head()

        CustomerId  Recency  Frequency  Monetary  cluster  is_high_risk
0     CustomerId_1       84          1     10000        0             1
1    CustomerId_10       84          1     10000        0             1
2  CustomerId_1001       90          5     30400        0             1
3  CustomerId_1002       26         11      4775        1             0
4  CustomerId_1003       12          6     32000        1             0

In [16]:
categorical_cols = [
    "CurrencyCode",
    "ProviderId",
    "ProductCategory",
    "ChannelId",
    "PricingStrategy"
]

In [17]:
target_df = rfm[
    ["CustomerId", "is_high_risk"]
]

In [18]:
df_target = df.merge(
    target_df,
    on="CustomerId",
    how="left"
)

In [19]:
df_target.head()

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CurrencyCode,CountryCode,ProviderId,ProductId,ProductCategory,ChannelId,Amount,Value,TransactionStartTime,PricingStrategy,FraudResult,is_high_risk
0,TransactionId_76871,BatchId_36123,AccountId_3957,SubscriptionId_887,CustomerId_4406,UGX,256,ProviderId_6,ProductId_10,airtime,ChannelId_3,1000.0,1000,2018-11-15T02:18:49Z,2,0,0
1,TransactionId_73770,BatchId_15642,AccountId_4841,SubscriptionId_3829,CustomerId_4406,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-20.0,20,2018-11-15T02:19:08Z,2,0,0
2,TransactionId_26203,BatchId_53941,AccountId_4229,SubscriptionId_222,CustomerId_4683,UGX,256,ProviderId_6,ProductId_1,airtime,ChannelId_3,500.0,500,2018-11-15T02:44:21Z,2,0,1
3,TransactionId_380,BatchId_102363,AccountId_648,SubscriptionId_2185,CustomerId_988,UGX,256,ProviderId_1,ProductId_21,utility_bill,ChannelId_3,20000.0,21800,2018-11-15T03:32:55Z,2,0,0
4,TransactionId_28195,BatchId_38780,AccountId_4841,SubscriptionId_3829,CustomerId_988,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-644.0,644,2018-11-15T03:34:21Z,2,0,0

In [20]:
woe = WOE()

woe.fit(
    df_target[categorical_cols],
    df_target["is_high_risk"]
)

WOE(mono_custom_binning={'PricingStrategy': array([0, 1, 2, 4], dtype=int64)},
    woe_bins={'PricingStrategy': {0: 1.730920246844631, 1: 0.3382608937904517,
                                  2: -1.0945123442021461e-05,
                                  4: -0.14693404236166793}})

In [21]:
rfm.to_csv(
    "../data/processed/rfm_features.csv",
    index=False
)